config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/login'
  get 'pages/authen', to: "pages#authen"
  get 'pages/logout', to: "pages#logout"
  resources :payments
  resources :search, only: [:index]
  resources :members do
    resources :payments
  end
  get :upcoming_payments, to: "members#upcoming_payments", as: :upcoming_payments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'payments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :payments, dependent: :destroy
  include PgSearch
  pg_search_scope :search, against: [:firstName, :lastName, :active]

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def login_required
    puts "SESSSSSSSSIOOOOOOOOOON SESSSSSSSSIOOOOOOOOOON SESSSSSSSSIOOOOOOOOOONSESSSSSSSSIOOOOOOOOOON SESSSSSSSSIOOOOOOOOOON"
    puts session.inspect
    redirect_to('/pages/home') unless session[:current_user] == "FORZA"
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :login_required, only: [:index, :edit, :update, :destroy]
  # GET /members
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  # GET /members
  # GET /members.json
  def index
    puts "SESSSSSSSSIOOOOOOOOOON"
    puts session[:admin]
    puts session[:current_user]
    if params[:query].present?
      @members = Member.search(params[:query])
    else
      @members = Member.all
    end
  end

  def innactive
    @members = @members.select{ |member| member.active }
    render(
      partial: 'list',
      locals: { members: @members }
    )
  end

  def upcoming_payments
    @allMembers = Member.all
    @members = []
    @allMembers.each do |m|
      puts Date.today + 14
      if m.nextPaymentDate <= Date.today + 14
        @members << m
      end
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @payments = Payment.where(member_id: @member.id)
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Miembro exitosamente creado.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Miembro exitosamente editado.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Miembro exitosamente eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      session.inspect
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:firstName, :lastName, :email, :phoneNumber, :paymentDay, :active, :nextPaymentDate, :search)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def logout
    session[:current_user] = ""
    redirect_to controller: "pages", action: "home"
  end

  def authen
    puts "ADASDASDASDASDASDA"
    params.inspect
    user = params[:pages][:email]
    password = params[:pages][:password]
    if user == "f@f.f" && password == "123"
      session[:current_user] = "FORZA"
      redirect_to controller: 'members', action: 'upcoming_payments'
      return
    end
    @member = Member.find_by(email:user)
    if !@member.nil?
      num = @member.phoneNumber
      num = num[num.length-4, 4]
      if num == password
        redirect_to @member
        return
      end
    end
    redirect_to pages_login_path, notice: 'Credenciales no validas'
  end

  def login
  end

  private

  def pages_params
    params.permit(:email, :password)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :login_required, only: [:show, :index, :edit, :update, :destroy]
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        @member = Member.find(payment_params[:member_id])
        @member.update(nextPaymentDate: @payment.date + 1.month)
        format.html { redirect_to payments_url, notice: 'Pago exitosamente creado.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payments_url, notice: 'Pago exitosamente editado.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Pago exitosamente eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :date, :member_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link rel = "stylesheet"
           href = "https://fonts.googleapis.com/icon?family=Material+Icons">
          <title>Forza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <nav>
      <div class="nav-wrapper">
        <%= link_to image_tag("forza_logo.jpg", alt: "logo", style: "height:100%"), '/', class: 'navbar-brand' %>
        <ul id="nav-mobile" class="right">
          <% if session[:current_user] == 'FORZA' %>
            <li> <%= link_to "Miembros", members_path %> </li>
            <li> <%= link_to "Pagos", payments_path %> </li>
            <li> <%= link_to "Pendientes", upcoming_payments_path %> </li>
            <li> <%= link_to "Logout", pages_logout_path %> </li>
          <% else %>
            <li> <%= link_to "Nosotros", pages_home_path %> </li>
            <li> <%= link_to "Acceso", pages_login_path %> </li>
          <%end %>
        </ul>
      </div>
    </nav>


  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstName, 'Nombre' %>
    <%= form.text_field :firstName %>
   </div>

  <div class="field">
    <%= form.label :lastName, 'Apellido' %>
    <%= form.text_field :lastName %>
  </div>

  <div class="field">
    <%= form.label :email, 'Correo' %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phoneNumber, 'Teléfono' %>
    <%= form.text_field :phoneNumber %>
  </div>

  <div class="field">
    <%= form.label :paymentDay, 'Fecha de corte' %>
    <%= form.number_field :paymentDay, value: Date.today.day %>
  </div>

  <div class="switch">
    <label>
      Activo
      <%= form.check_box :active, checked: "checked" %>
      <span class="lever"></span>
    </label>
  </div>
  <br>
  <div class="field">
    <%= form.label :nextPaymentDate, 'Día siguiente de pago' %>
    <%= form.text_field :nextPaymentDate, class: "datepicker", value: Date.today.next_month%>
  </div>

  <div class="actions waves-effect waves-light btn">
    <%= form.submit 'Guardar' %>
  </div>
<% end %>

app/views/members/_list.html.erb
<span>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Fecha de corte</th>
      <th>Status</th>
      <th>Siguiente pago</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.firstName %></td>
        <td><%= member.lastName %></td>
        <td><%= member.email %></td>
        <td><%= member.phoneNumber %></td>
        <td><%= member.paymentDay %></td>
        <td>
          <%= 'Activo' if member.active %>
          <%= 'Inactivo' if !member.active %>
        </td>
        <td><%= member.nextPaymentDate %></td>
        <td><%= link_to 'Registrar pago', "members/#{member.id}/payments/new" %></td>
        <td><%= link_to 'Perfil', member %></td>
        <td><%= link_to 'Editar', edit_member_path(member) %></td>
        <td><%= link_to 'Eliminar', member, method: :delete, data: { confirm: '¿Desea continuar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/edit.html.erb
<h1>Editar miembro</h1>

<%= render 'form', member: @member %>

<%= link_to 'Ver', @member %> |
<%= link_to 'Atrás', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Miembros</h1>
<%= form_tag(members_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :query, params[:query], placeholder: "Buscar nombre" %>
<%= submit_tag "Buscar", class: "actions waves-effect waves-light btn" %>
<% end %>
<br>
<div>
<%= button_to 'Agregar miembro', new_member_path, method: :get, class: "actions waves-effect waves-light btn right" %>
</div>
<%= render(
  partial: 'list',
  locals: { members: @members }
) %>

app/views/members/new.html.erb
<h1>Nuevo Miembro</h1>

<%= render 'form', member: @member %>

<%= link_to 'Atras', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<h5 class = "collection-item">
  <%= @member.firstName %> <%= @member.lastName %>
</h5>

<p>
  <strong>Correo:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @member.phoneNumber %>
</p>

<p>
  <strong>Fecha de corte:</strong>
  <%= @member.paymentDay %>
</p>

<p>
  <%= 'Activo' if @member.active %>
  <%= 'Inactivo' if !@member.active %>
</p>

<p>
  <strong>Día siguiente de pago:</strong>
  <%= @member.nextPaymentDate %>
</p>
<% if session[:current_user] == "FORZA" %>
<%= link_to 'Editar', edit_member_path(@member) %> |
<%= link_to 'Atrás', members_path %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.date %></td>
        <td><%= link_to 'Editar', edit_payment_path(payment) %></td>
        <td><%= link_to 'Eliminar', payment, method: :delete, data: { confirm: '¿Desea continuar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/upcoming_payments.html.erb
<p id="notice"><%= notice %></p>

<h1>Pagos pendientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Dia de pago</th>
      <th>Status</th>
      <th>Siguiente pago</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.firstName %></td>
        <td><%= member.lastName %></td>
        <td><%= member.email %></td>
        <td><%= member.phoneNumber %></td>
        <td><%= member.paymentDay %></td>
        <td>
          <%= 'Activo' if member.active %>
          <%= 'Inactivo' if !member.active %>
        </td>
        <td><%= member.nextPaymentDate %></td>
        <td><%= link_to 'Registrar pago', "members/#{member.id}/payments/new" %></td>
        <td><%= link_to 'Perfil', member %></td>
        <td><%= link_to 'Editar', edit_member_path(member) %></td>
        <td><%= link_to 'Eliminar', member, method: :delete, data: { confirm: '¿Desea continuar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/home.html.erb
<h4>Sobre nosotros</h4>
Somos un gimnasio de calistenia abierto para todo el público.



<h5>Nos especializamos en ayudarte a alcanzar y exceder tus metas</h5>
Contamos con excelentes coaches que le proveen a nuestros miembros una rutina especializada. Adicionalmente, nuestra nutrióloga le ofrece consejos a nuestros miembros para que vivan y entrenen sanamente.

<h5>Contacto</h5>
Whatsapp: 01 81 2511 9160
<br>
Facebook: /forzagravitygym

<h5>Horarios</h5>
lunes     6:00-10:00, 16:00-22:00
<br>
martes    6:00-10:00, 16:00-22:00
<br>
miércoles 6:00-10:00, 16:00-22:00
<br>
jueves    6:00-10:00, 16:00-22:00
<br>
viernes   6:00-10:00, 16:00-22:00
<br>
sábado    10:00-14:00
<br>
domingo   Cerrado

<h5>Ubicación</h5>
Lázaro Cárdenas 4328-A (5,87 km)
64930 Monterrey


<div class="carousel carousel-slider" id="demo-carousel-indicators" data-indicators="true" style = "min-height: 900px">
   <a class="carousel-item" href="#one!">
     <%=image_tag("forza.jpg") %>
   </a>
   <a class="carousel-item" href="#two!">
     <%=image_tag("forza_2.jpg") %>
   </a>
   <a class="carousel-item" href="#two!">
     <%=image_tag("forza_3.jpg") %>
   </a>
   <a class="carousel-item" href="#two!">
     <%=image_tag("forza_4.jpg") %>
   </a>
   <a class="carousel-item" href="#two!">
     <%=image_tag("forza_5.jpg") %>
   </a>
   <a class="carousel-item" href="#two!">
     <%=image_tag("forza_6.jpg") %>
   </a>

</div>

app/views/pages/login.html.erb
<h1>Log in</h1>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:pages, url: pages_authen_url, method: :get ) do |f| %>

      <%= f.label :email, 'Correo'%>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, 'Contraseña' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Cantidad %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :Fecha %>
    <%= form.text_field :date, class: "datepicker", value: Date.today%>
  </div>

  <div  style="display:none;">
  <%= form.text_field :member_id, as: :hidden, value: params[:member_id] %>
</div>


  <div>
    <%= form.submit 'Guardar', class: "actions waves-effect waves-light btn" %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editar Pago</h1>

<%= render 'form', payment: @payment %>

<br>

<%= link_to 'Atrás', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pagos</h1>

<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Fecha</th>
      <th>Miembro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.date %></td>
        <td><%= "#{Member.find(payment.member_id).firstName} #{Member.find(payment.member_id).lastName }" %></td>
        <td><%= link_to 'Editar', "members/#{payment.member_id}/payments/#{payment.id}/edit" %></td>
        <td><%= link_to 'Eliminar', payment, method: :delete, data: { confirm: '¿Desea continuar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/payments/new.html.erb
<h1>Nuevo Pago</h1>

<%= render 'form', payment: @payment %>
<br>
<%= link_to 'Atrás', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @payment.date %>
</p>

<p>
  <strong>Member:</strong>
  <%= @payment.member_id %>
</p>

<%= link_to 'Editar', edit_payment_path(@payment) %> |
<%= link_to 'Atrás', payments_path %>